In [71]:
import numpy as np

arr = [1,2,3,4]

narr = np.array(arr)
narr

array([1, 2, 3, 4])

In [72]:
arr_2d = [[1,2,4,4],[4,5,6,6],[5,6,7,8]]
narr_2d = np.array(arr_2d)
narr_2d

array([[1, 2, 4, 4],
       [4, 5, 6, 6],
       [5, 6, 7, 8]])

In [73]:
np.arange(6,49,2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48])

In [74]:
np.zeros(33)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
np.ones(34)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
np.linspace(4,3,6)

array([4. , 3.8, 3.6, 3.4, 3.2, 3. ])

In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
from numpy import random

In [79]:
np.random.rand(10,2)

array([[0.7700411 , 0.53429075],
       [0.82300322, 0.65478309],
       [0.80657702, 0.61968564],
       [0.74837556, 0.29287768],
       [0.78939097, 0.66151147],
       [0.44833584, 0.58471095],
       [0.59735992, 0.12138516],
       [0.47143974, 0.22239752],
       [0.31562225, 0.25716925],
       [0.44096015, 0.5489017 ]])

In [80]:
import numpy as np

print(np.random.randn(10))  # normal
print(np.random.rand(10))   # uniform

[-0.843075   -0.15946414 -0.48271961 -0.12798162 -0.90688607  0.18994747
  1.28295062  0.48085383  1.05005616 -0.20545627]
[0.52338586 0.88695175 0.98668117 0.18546961 0.07577238 0.91512891
 0.77781905 0.50449823 0.85937326 0.00337976]


In [81]:
np.random.randint(7,23 ,size=(3,4))

array([[22, 10, 12, 16],
       [17, 16, 11, 22],
       [ 7, 17, 12, 12]], dtype=int32)

In [85]:
import numpy as np

matrix = np.array([
    [100, 200, 300, 400],
    [500, 600, 700, 800],
    [900, 100, 200, 300],
    [848,848,939,575,]
])

In [86]:
matrix

array([[100, 200, 300, 400],
       [500, 600, 700, 800],
       [900, 100, 200, 300],
       [848, 848, 939, 575]])

In [91]:
new_array = []
rows = matrix[2:4,1:4]
rows


array([[100, 200, 300],
       [848, 939, 575]])