In [2]:
import numpy as np

arr = [1,2,3,4]

narr = np.array(arr)
narr

array([1, 2, 3, 4])

In [6]:
arr_2d = [[1,2,4,4],[4,5,6,6],[5,6,7,8]]
narr_2d = np.array(arr_2d)
narr_2d

array([[1, 2, 4, 4],
       [4, 5, 6, 6],
       [5, 6, 7, 8]])

In [9]:
np.arange(6,49,2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48])

In [11]:
np.zeros(33)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(34)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])